export const countries =[
    { "name": "Afghanistan", "code": "+93", "flag": "🇦🇫", "id": "AF" },
    { "name": "Albania", "code": "+355", "flag": "🇦🇱", "id": "AL" },
    { "name": "Algeria", "code": "+213", "flag": "🇩🇿", "id": "DZ" },
    { "name": "Andorra", "code": "+376", "flag": "🇦🇩", "id": "AD" },
    { "name": "Angola", "code": "+244", "flag": "🇦🇴", "id": "AO" },
    { "name": "Antigua and Barbuda", "code": "+1-268", "flag": "🇦🇬", "id": "AG" },
    { "name": "Argentina", "code": "+54", "flag": "🇦🇷", "id": "AR" },
    { "name": "Armenia", "code": "+374", "flag": "🇦🇲", "id": "AM" },
    { "name": "Australia", "code": "+61", "flag": "🇦🇺", "id": "AU" },
    { "name": "Austria", "code": "+43", "flag": "🇦🇹", "id": "AT" },
    { "name": "Azerbaijan", "code": "+994", "flag": "🇦🇿", "id": "AZ" },
    { "name": "Bahamas", "code": "+1-242", "flag": "🇧🇸", "id": "BS" },
    { "name": "Bahrain", "code": "+973", "flag": "🇧🇭", "id": "BH" },
    { "name": "Bangladesh", "code": "+880", "flag": "🇧🇩", "id": "BD" },
    { "name": "Barbados", "code": "+1-246", "flag": "🇧🇧", "id": "BB" },
    { "name": "Belarus", "code": "+375", "flag": "🇧🇾", "id": "BY" },
    { "name": "Belgium", "code": "+32", "flag": "🇧🇪", "id": "BE" },
    { "name": "Belize", "code": "+501", "flag": "🇧🇿", "id": "BZ" },
    { "name": "Benin", "code": "+229", "flag": "🇧🇯", "id": "BJ" },
    { "name": "Bhutan", "code": "+975", "flag": "🇧🇹", "id": "BT" },
    { "name": "Bolivia", "code": "+591", "flag": "🇧🇴", "id": "BO" },
    { "name": "Bosnia and Herzegovina", "code": "+387", "flag": "🇧🇦", "id": "BA" },
    { "name": "Botswana", "code": "+267", "flag": "🇧🇼", "id": "BW" },
    { "name": "Brazil", "code": "+55", "flag": "🇧🇷", "id": "BR" },
    { "name": "Brunei", "code": "+673", "flag": "🇧🇳", "id": "BN" },
    { "name": "Bulgaria", "code": "+359", "flag": "🇧🇬", "id": "BG" },
    { "name": "Burkina Faso", "code": "+226", "flag": "🇧🇫", "id": "BF" },
    { "name": "Burundi", "code": "+257", "flag": "🇧🇮", "id": "BI" },
    { "name": "Cabo Verde", "code": "+238", "flag": "🇨🇻", "id": "CV" },
    { "name": "Cambodia", "code": "+855", "flag": "🇰🇭", "id": "KH" },
    { "name": "Cameroon", "code": "+237", "flag": "🇨🇲", "id": "CM" },
    { "name": "Canada", "code": "+1", "flag": "🇨🇦", "id": "CA" },
    { "name": "Central African Republic", "code": "+236", "flag": "🇨🇫", "id": "CF" },
    { "name": "Chad", "code": "+235", "flag": "🇹🇩", "id": "TD" },
    { "name": "Chile", "code": "+56", "flag": "🇨🇱", "id": "CL" },
    { "name": "China", "code": "+86", "flag": "🇨🇳", "id": "CN" },
    { "name": "Colombia", "code": "+57", "flag": "🇨🇴", "id": "CO" },
    { "name": "Comoros", "code": "+269", "flag": "🇰🇲", "id": "KM" },
    { "name": "Congo (Congo-Brazzaville)", "code": "+242", "flag": "🇨🇬", "id": "CG" },
    { "name": "Congo (Democratic Republic)", "code": "+243", "flag": "🇨🇩", "id": "CD" },
    { "name": "Costa Rica", "code": "+506", "flag": "🇨🇷", "id": "CR" },
    { "name": "Croatia", "code": "+385", "flag": "🇭🇷", "id": "HR" },
    { "name": "Cuba", "code": "+53", "flag": "🇨🇺", "id": "CU" },
    { "name": "Cyprus", "code": "+357", "flag": "🇨🇾", "id": "CY" },
    { "name": "Czech Republic", "code": "+420", "flag": "🇨🇿", "id": "CZ" },
    { "name": "Denmark", "code": "+45", "flag": "🇩🇰", "id": "DK" },
    { "name": "Djibouti", "code": "+253", "flag": "🇩🇯", "id": "DJ" },
    { "name": "Dominica", "code": "+1-767", "flag": "🇩🇲", "id": "DM" },
    { "name": "Dominican Republic", "code": "+1-809", "flag": "🇩🇴", "id": "DO" },
    { "name": "Ecuador", "code": "+593", "flag": "🇪🇨", "id": "EC" },
    { "name": "Egypt", "code": "+20", "flag": "🇪🇬", "id": "EG" },
    { "name": "El Salvador", "code": "+503", "flag": "🇸🇻", "id": "SV" },
    { "name": "Equatorial Guinea", "code": "+240", "flag": "🇬🇶", "id": "GQ" },
    { "name": "Eritrea", "code": "+291", "flag": "🇪🇷", "id": "ER" },
    { "name": "Estonia", "code": "+372", "flag": "🇪🇪", "id": "EE" },
    { "name": "Eswatini", "code": "+268", "flag": "🇸🇿", "id": "SZ" },
    { "name": "Ethiopia", "code": "+251", "flag": "🇪🇹", "id": "ET" },
    { "name": "Fiji", "code": "+679", "flag": "🇫🇯", "id": "FJ" },
    { "name": "Finland", "code": "+358", "flag": "🇫🇮", "id": "FI" },
    { "name": "France", "code": "+33", "flag": "🇫🇷", "id": "FR" },
    { "name": "Gabon", "code": "+241", "flag": "🇬🇦", "id": "GA" },
    { "name": "Gambia", "code": "+220", "flag": "🇬🇲", "id": "GM" },
    { "name": "Georgia", "code": "+995", "flag": "🇬🇪", "id": "GE" },
    { "name": "Germany", "code": "+49", "flag": "🇩🇪", "id": "DE" },
    { "name": "Ghana", "code": "+233", "flag": "🇬🇭", "id": "GH" },
    { "name": "Greece", "code": "+30", "flag": "🇬🇷", "id": "GR" },
    { "name": "Grenada", "code": "+1-473", "flag": "🇬🇩", "id": "GD" },
    { "name": "Guatemala", "code": "+502", "flag": "🇬🇹", "id": "GT" },
    { "name": "Guinea", "code": "+224", "flag": "🇬🇳", "id": "GN" },
    { "name": "Guinea-Bissau", "code": "+245", "flag": "🇬🇼", "id": "GW" },
    { "name": "Guyana", "code": "+592", "flag": "🇬🇾", "id": "GY" },
    { "name": "Haiti", "code": "+509", "flag": "🇭🇹", "id": "HT" },
    { "name": "Honduras", "code": "+504", "flag": "🇭🇳", "id": "HN" },
    { "name": "Hungary", "code": "+36", "flag": "🇭🇺", "id": "HU" },
    { "name": "Iceland", "code": "+354", "flag": "🇮🇸", "id": "IS" },
    { "name": "India", "code": "+91", "flag": "🇮🇳", "id": "IN" },
    { "name": "Indonesia", "code": "+62", "flag": "🇮🇩", "id": "ID" },
    { "name": "Iran", "code": "+98", "flag": "🇮🇷", "id": "IR" },
    { "name": "Iraq", "code": "+964", "flag": "🇮🇶", "id": "IQ" },
    { "name": "Ireland", "code": "+353", "flag": "🇮🇪", "id": "IE" },
    { "name": "Israel", "code": "+972", "flag": "🇮🇱", "id": "IL" },
    { "name": "Italy", "code": "+39", "flag": "🇮🇹", "id": "IT" },
    { "name": "Jamaica", "code": "+1-876", "flag": "🇯🇲", "id": "JM" },
    { "name": "Japan", "code": "+81", "flag": "🇯🇵", "id": "JP" },
    { "name": "Jordan", "code": "+962", "flag": "🇯🇴", "id": "JO" },
    { "name": "Kazakhstan", "code": "+7", "flag": "🇰🇿", "id": "KZ" },
    { "name": "Kenya", "code": "+254", "flag": "🇰🇪", "id": "KE" },
    { "name": "Kiribati", "code": "+686", "flag": "🇰🇮", "id": "KI" },
    { "name": "Korea (North)", "code": "+850", "flag": "🇰🇵", "id": "KP" },
    { "name": "Korea (South)", "code": "+82", "flag": "🇰🇷", "id": "KR" },
    { "name": "Kuwait", "code": "+965", "flag": "🇰🇼", "id": "KW" },
    { "name": "Kyrgyzstan", "code": "+996", "flag": "🇰🇬", "id": "KG" },
    { "name": "Laos", "code": "+856", "flag": "🇱🇦", "id": "LA" },
    { "name": "Latvia", "code": "+371", "flag": "🇱🇻", "id": "LV" },
    { "name": "Lebanon", "code": "+961", "flag": "🇱🇧", "id": "LB" },
    { "name": "Lesotho", "code": "+266", "flag": "🇱🇸", "id": "LS" },
    { "name": "Liberia", "code": "+231", "flag": "🇱🇸", "id": "LR" },
    { "name": "Libya", "code": "+218", "flag": "🇱🇾", "id": "LY" },
    { "name": "Liechtenstein", "code": "+423", "flag": "🇱🇮", "id": "LI" },
    { "name": "Lithuania", "code": "+370", "flag": "🇱🇹", "id": "LT" },
    { "name": "Luxembourg", "code": "+352", "flag": "🇱🇺", "id": "LU" },
    { "name": "Madagascar", "code": "+261", "flag": "🇲🇬", "id": "MG" },
    { "name": "Malawi", "code": "+265", "flag": "🇲🇼", "id": "MW" },
    { "name": "Malaysia", "code": "+60", "flag": "🇲🇾", "id": "MY" },
    { "name": "Maldives", "code": "+960", "flag": "🇲🇻", "id": "MV" },
    { "name": "Mali", "code": "+223", "flag": "🇲🇱", "id": "ML" },
    { "name": "Malta", "code": "+356", "flag": "🇲🇹", "id": "MT" },
    { "name": "Marshall Islands", "code": "+692", "flag": "🇲🇭", "id": "MH" },
    { "name": "Mauritania", "code": "+222", "flag": "🇲🇷", "id": "MR" },
    { "name": "Mauritius", "code": "+230", "flag": "🇲🇺", "id": "MU" },
    { "name": "Mexico", "code": "+52", "flag": "🇲🇽", "id": "MX" },
    { "name": "Micronesia", "code": "+691", "flag": "🇫🇲", "id": "FM" },
    { "name": "Moldova", "code": "+373", "flag": "🇲🇩", "id": "MD" },
    { "name": "Monaco", "code": "+377", "flag": "🇲🇨", "id": "MC" },
    { "name": "Mongolia", "code": "+976", "flag": "🇲🇳", "id": "MN" },
    { "name": "Montenegro", "code": "+382", "flag": "🇲🇪", "id": "ME" },
    { "name": "Morocco", "code": "+212", "flag": "🇲🇦", "id": "MA" },
    { "name": "Mozambique", "code": "+258", "flag": "🇲🇿", "id": "MZ" },
    { "name": "Myanmar", "code": "+95", "flag": "🇲🇲", "id": "MM" },
    { "name": "Namibia", "code": "+264", "flag": "🇳🇦", "id": "NA" },
    { "name": "Nauru", "code": "+674", "flag": "🇳🇷", "id": "NR" },
    { "name": "Nepal", "code": "+977", "flag": "🇳🇵", "id": "NP" },
    { "name": "Netherlands", "code": "+31", "flag": "🇳🇱", "id": "NL" },
    { "name": "New Zealand", "code": "+64", "flag": "🇳🇿", "id": "NZ" },
    { "name": "Nicaragua", "code": "+505", "flag": "🇳🇮", "id": "NI" },
    { "name": "Niger", "code": "+227", "flag": "🇳🇪", "id": "NE" },
    { "name": "Nigeria", "code": "+234", "flag": "🇳🇬", "id": "NG" },
    { "name": "North Macedonia", "code": "+389", "flag": "🇲🇰", "id": "MK" },
    { "name": "Norway", "code": "+47", "flag": "🇳🇴", "id": "NO" },
    { "name": "Oman", "code": "+968", "flag": "🇴🇲", "id": "OM" },
    { "name": "Pakistan", "code": "+92", "flag": "🇵🇰", "id": "PK" },
    { "name": "Palau", "code": "+680", "flag": "🇵🇼", "id": "PW" },
    { "name": "Panama", "code": "+507", "flag": "🇵🇦", "id": "PA" },
    { "name": "Papua New Guinea", "code": "+675", "flag": "🇵🇬", "id": "PG" },
    { "name": "Paraguay", "code": "+595", "flag": "🇵🇾", "id": "PY" },
    { "name": "Peru", "code": "+51", "flag": "🇵🇪", "id": "PE" },
    { "name": "Philippines", "code": "+63", "flag": "🇵🇭", "id": "PH" },
    { "name": "Poland", "code": "+48", "flag": "🇵🇱", "id": "PL" },
    { "name": "Portugal", "code": "+351", "flag": "🇵🇹", "id": "PT" },
    { "name": "Qatar", "code": "+974", "flag": "🇶🇦", "id": "QA" }
  ]
  